type: object
required:
  - quotationDays
  - quotationTerm
properties:
  quotationDays:
    type: integer
    format: int32
    description: Indica se o fundo estabelece um período em que o investidor não pode resgatar os recursos aplicados no fundo. Caso ocorra resgate antes do período, o investidor perderá a rentabilidade do período.
    minimum: 0
    example: 60
  quotationTerm:
    $ref: ../enum/EnumInvestmentsFundGeneralConditionsTermType.yaml
additionalProperties: false
