type: object
properties:
  interval:
    $ref: ./ApplicationIntervals.yaml
  rate:
    type: string
    pattern: (^[0-9](\.[0-9]{4})$|^NA$)
    maxLength: 6
    description: |
      Percentual que corresponde a mediana (taxa efetiva) cobrada do cliente pela utilização do crédito rotativo, no intervalo informado.
    example: 0.8700
  customers:
    $ref: ./Customer.yaml
required:
  - interval
  - indexer
  - customers
